const ADD_TO_CART = "ADD_TO_CART";
const REMOVE_FROM_CART = "REMOVE_FROM_CART";
const UPDATE_TOTAL_PRICE = "UPDATE_TOTAL_PRICE";
const UPDATE_TOTAL_PRODUCTS = "UPDATE_TOTAL_PRODUCTS";

export { ADD_TO_CART, REMOVE_FROM_CART, UPDATE_TOTAL_PRICE, UPDATE_TOTAL_PRODUCTS };